version: '3.8'

services:
  bot:
    build: .
    container_name: spread-bot
    restart: always
    volumes:
      - ./bot_state.json:/app/bot_state.json
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 